package trackour.trackour.model.user;
import java.time.LocalDateTime;
import java.util.ArrayList;
// import java.util.Collection;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
// import java.util.stream.Collectors;
import java.util.UUID;

import org.hibernate.annotations.OnDelete;
import org.hibernate.annotations.OnDeleteAction;
import org.springframework.format.annotation.DateTimeFormat;

import com.fasterxml.jackson.annotation.JsonIgnore;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.JoinTable;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import jakarta.transaction.Transactional;
import trackour.trackour.model.project.Project;

@Entity
@Table(
    name="Users", 
    uniqueConstraints=
        @UniqueConstraint(
            columnNames={"uid", "username", "email"}
            )
        )
public class User {
    
    @Id
    /**
     * so they aren't visible when printed 
     * the id is not even generated by the client so
     * it's displayed as "null" and so it's a preference
     * to not allow that json property to be displayed
     */
    @JsonIgnore
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "uid")
    private Long uid;

    // Change this to User instead of Friendship
    @ManyToMany(fetch = FetchType.EAGER, cascade = CascadeType.MERGE)
    @JoinTable(
        name = "friends_with",
        joinColumns = @JoinColumn(name = "user_id"),
        inverseJoinColumns = @JoinColumn(name = "friend_id")
    )
    private List<User> friends;

    // one user has many projects
    @OneToMany(
        mappedBy = "owner", 
        fetch = FetchType.EAGER, 
        cascade = CascadeType.MERGE
        )
    @OnDelete(action = OnDeleteAction.CASCADE)
    @Column(name="owned_projects")
    private List<Project> ownedProjects;

    @Column(name = "username")
    private String username;

    @JsonIgnore
    @Column(name = "passwordResetToken")
    private String passwordResetToken;

    @DateTimeFormat
    @Column(name = "passwordResetTokenCreatedAt")
    private LocalDateTime passwordResetTokenCreatedAt;
    
    private String displayName;

    // so they aren't visible when printed
    @JsonIgnore
    private String password;

    @Column(name = "email")
    private String email;
    
    // roles are now stored in a set directly in the roles column of the users table
    @Enumerated(EnumType.STRING)
    private Set<Role> roles;

    // ---------------------------methods------------------------------------------------

    public User() {
        initCollections();
    }
    
    public User(Long id) {
        this.uid = id;
        initCollections();
    }

    public User(String username, String displayName, String password, String email, Set<Role> roles) {
        this.username = username;
        this.displayName = displayName;
        this.password = password;
        this.email = email;
        this.initCollections();
    }

    public User(String username, String displayName, String password, String email) {
        this.username = username;
        this.displayName = displayName;
        this.password = password;
        this.email = email;
        ownedProjects = new ArrayList<>();
        this.initCollections();
    }
    private void initCollections() {

        this.ownedProjects = new ArrayList<>();
        this.friends = new ArrayList<>();
        
        // initialize default role as ["USER"]
        Set<Role> defaultRole = new HashSet<>();
        defaultRole.add(Role.USER);
        // defaultRole.add(Role.ADMIN);
        setRoles(defaultRole);
    }

    // getters and setters
    public List<User> getFriendships() {
        return friends;
    }
    
    public void setFriendships(List<User> friends) {
        this.friends = friends;
    }

    @Transactional
    public List<Project> getOwnedProjects() {
        return ownedProjects;
    }

    @Transactional
    public void setOwnedProjects(List<Project> ownedProjects) {
        this.ownedProjects = ownedProjects;
    }

    public void setRoles(Set<Role> roles) {
        this.roles = roles;
    }

    public Set<Role> getRoles() {
        return this.roles;
    }
    

    public void setUid(Long uid) {
        this.uid = uid;
    }

    public Long getUid() {
        return this.uid;
    }
    

    public void setUsername(String username) {
        this.username = username;
    }

    public String getUsername() {
        return this.username;
    }
    

    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    public String getDisplayName() {
        return this.displayName;
    }
    

    public void setPassword(String password) {
        this.password = password;
    }

    public String getPassword() {
        return this.password;
    }
    

    public void setPasswordResetToken(String passwordResetToken) {
        this.passwordResetToken = passwordResetToken;
    }

    public void generatePasswordResetToken() {
        this.passwordResetToken = UUID.randomUUID().toString();
    }

    public String getPasswordResetToken() {
        return this.passwordResetToken;
    }

    public LocalDateTime getPasswordResetTokenCreatedAt() {
        return this.passwordResetTokenCreatedAt;
    }

    public void setPasswordResetTokenCreatedAt(LocalDateTime passwordResetTokenCreatedAt) { 
        this.passwordResetTokenCreatedAt = passwordResetTokenCreatedAt;
    }    

    public void setEmail(String email) {
        this.email = email;
    }

    public String getEmail() {
        return this.email;
    }
}
